=== ghasemel/Qt-Reporting-Tools/reportpp-master/reportpp-master/xml-schema/reportpp.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://github.com/mmickey/reportpp"
           xmlns="https://github.com/mmickey/reportpp" 
           elementFormDefault="qualified">

  <xs:simpleType name="tPageFormat">
    <xs:annotation>
      <xs:documentation>
        Default page sizes as defined in libHaru include files.
        Only reports with the same page format for all report pages are
        supported (by now, at least)
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="letter"/>
      <xs:enumeration value="legal"/>
      <xs:enumeration value="a3"/>
      <xs:enumeration value="a4"/>
      <xs:enumeration value="a5"/>
      <xs:enumeration value="b4"/>
      <xs:enumeration value="b5"/>
      <xs:enumeration value="executive"/>
      <xs:enumeration value="us4x6"/>
      <xs:enumeration value="us4x8"/>
      <xs:enumeration value="us5x7"/>
      <xs:enumeration value="comm10"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="textElement">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="x" type="xs:float"/>
        <xs:attribute name="y" type="xs:float"/>
        <xs:attribute name="fontName" type="xs:string"/>
        <xs:attribute name="fontSize" type="xs:integer"/>
        <xs:attribute name="fontStyle" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="shapeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="rectangle"/>
      <xs:enumeration value="circle"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="shapeElement">
    <xs:attribute name="type" type="shapeType"/>
    <xs:attribute name="x" type="xs:float"/>
    <xs:attribute name="y" type="xs:float"/>
    <xs:attribute name="width" type="xs:float"/>
    <xs:attribute name="height" type="xs:float"/>
  </xs:complexType>

  <xs:complexType name="imageElement">
    <xs:attribute name="src" type="xs:string"/>
    <xs:attribute name="x" type="xs:float"/>
    <xs:attribute name="y" type="xs:float"/>
    <xs:attribute name="width" type="xs:float"/>
    <xs:attribute name="height" type="xs:float"/>
  </xs:complexType>

  <xs:complexType name="pageBlock">
    <xs:annotation>
      <xs:documentation>
        Represents a single page block. A block is a container for shapes,
        labels and other text/graphical elements.
      </xs:documentation>
    </xs:annotation>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="text" type="textElement"/>
      <xs:element name="label" type="textElement"/>
      <xs:element name="shape" type="shapeElement"/>
      <xs:element name="image" type="imageElement"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="ReportPage">
    <xs:sequence>
      <xs:element name="block" type="pageBlock" maxOccurs="unbounded"/>
    </xs:sequence>
    <!-- each report page can override the report settings for page format -->
    <xs:attribute name="pageFormat" type="tPageFormat"/>
    <xs:attribute name="marginTop"    type="xs:float"/>
    <xs:attribute name="marginBottom" type="xs:float"/>
    <xs:attribute name="marginLeft"   type="xs:float"/>
    <xs:attribute name="marginRight"  type="xs:float"/>
  </xs:complexType>

  <xs:complexType name="ReportType">
    <xs:sequence>
      <xs:element name="frontPage" type="ReportPage" minOccurs="0"/>
      <xs:element name="firstPage" type="ReportPage" minOccurs="0"/>
      <xs:element name="dataPage"  type="ReportPage"/>
      <xs:element name="lastPage"  type="ReportPage" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="pageFormat" type="tPageFormat" default="a4"/>
    <xs:attribute name="marginTop"    type="xs:float" default="0"/>
    <xs:attribute name="marginBottom" type="xs:float" default="0"/>
    <xs:attribute name="marginLeft"   type="xs:float" default="0"/>
    <xs:attribute name="marginRight"  type="xs:float" default="0"/>
  </xs:complexType>

  <xs:element name="report" type="ReportType"/>
</xs:schema>

=== ghasemel/Qt-Reporting-Tools/reportpp-master/reportpp-master/test/test1/test3.xml
<?xml version="1.0" encoding="UTF-8"?>
<report xmlns="https://github.com/mmickey/reportpp"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://github.com/mmickey/reportpp ../../xml-schema/reportpp.xsd"
        marginTop="15"
        marginBottom="10"
        marginLeft="5"
        marginRight="5">
  <frontPage>
    <block>
      <text x="15" y="15" fontName="Helvetica" fontSize="20" fontStyle="italic">Cover Page</text>
      <shape type="rectangle" x="10" y="10" width="45" height="50"/>
      <text x="15" y="45" fontName="Helvetica" fontSize="5" fontStyle="bold">by mickey</text>
    </block>
  </frontPage>

  <dataPage>
    <block/>
  </dataPage>
</report>
